"""auto_migration_20250519_050031

Revision ID: 7fcbf8eab775
Revises: bd5ea5a256d8
Create Date: 2025-05-19 05:00:32.572749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcbf8eab775'
down_revision: Union[str, None] = 'bd5ea5a256d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
